"""
Theta Function Scan: Find the Wilson line shift z_0 where
|theta_1(z_0 | omega)| = ln(3)/sqrt(2)

If z_0 has a nice closed form, it supports the conjecture.
"""


# This file was *autogenerated* from the file theta_scan.sage
from sage.all_cmdline import *   # import sage library

_sage_const_200 = Integer(200); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0p778241706886285 = RealNumber('0.778241706886285'); _sage_const_100 = Integer(100); _sage_const_0 = Integer(0); _sage_const_300 = Integer(300); _sage_const_1 = Integer(1); _sage_const_45 = Integer(45); _sage_const_0p20 = RealNumber('0.20'); _sage_const_0p22 = RealNumber('0.22'); _sage_const_0p24 = RealNumber('0.24'); _sage_const_0p25 = RealNumber('0.25'); _sage_const_0p26 = RealNumber('0.26'); _sage_const_0p27 = RealNumber('0.27'); _sage_const_0p2750 = RealNumber('0.2750'); _sage_const_0p2770 = RealNumber('0.2770'); _sage_const_0p2778 = RealNumber('0.2778'); _sage_const_0p28 = RealNumber('0.28'); _sage_const_0p29 = RealNumber('0.29'); _sage_const_0p30 = RealNumber('0.30'); _sage_const_0p32 = RealNumber('0.32'); _sage_const_0p34 = RealNumber('0.34'); _sage_const_0p36 = RealNumber('0.36'); _sage_const_0p38 = RealNumber('0.38'); _sage_const_0p40 = RealNumber('0.40'); _sage_const_0p42 = RealNumber('0.42'); _sage_const_0p44 = RealNumber('0.44'); _sage_const_0p46 = RealNumber('0.46'); _sage_const_0p48 = RealNumber('0.48'); _sage_const_0p50 = RealNumber('0.50'); _sage_const_5 = Integer(5); _sage_const_18 = Integer(18); _sage_const_0p0001 = RealNumber('0.0001'); _sage_const_0p15 = RealNumber('0.15'); _sage_const_50 = Integer(50); _sage_const_0p00005 = RealNumber('0.00005'); _sage_const_60 = Integer(60); _sage_const_30 = Integer(30); _sage_const_0p005 = RealNumber('0.005'); _sage_const_4 = Integer(4); _sage_const_29 = Integer(29); _sage_const_13 = Integer(13); _sage_const_0p01 = RealNumber('0.01'); _sage_const_36 = Integer(36); _sage_const_6 = Integer(6); _sage_const_12 = Integer(12); _sage_const_8 = Integer(8); _sage_const_0p5 = RealNumber('0.5')
from sage.all import *

R = RealField(_sage_const_200 )
C = ComplexField(_sage_const_200 )

pi_val = R(pi)
omega = C(exp(_sage_const_2  * pi * I / _sage_const_3 ))
target = R(ln(R(_sage_const_3 ))) / R(sqrt(R(_sage_const_2 )))

print(f"Target: ln(3)/sqrt(2) = {float(target):.15f}")
print(f"|theta_1(5/18|omega)| = 0.778241706886285")
print(f"Gap: {float(abs(R(_sage_const_0p778241706886285 ) - target)/target * _sage_const_100 ):.4f}%")
print()

# Precompute q
q = C(exp(_sage_const_2  * pi * I * omega))

def theta1_abs(z):
    """Compute |theta_1(z | omega)| for real z."""
    z_r = R(z)
    result = C(_sage_const_0 )
    for n in range(_sage_const_300 ):
        sign = (-_sage_const_1 )**n
        q_pow = (n + R(_sage_const_1 )/R(_sage_const_2 ))**_sage_const_2  / R(_sage_const_2 )
        s_arg = (_sage_const_2 *n + _sage_const_1 ) * pi_val * z_r
        result += C(sign) * q**q_pow * C(sin(s_arg))
    return abs(_sage_const_2  * result)

# Binary search for z_0 where |theta_1(z_0|omega)| = ln(3)/sqrt(2)
print("Binary search for z_0 where |theta_1(z_0 | omega)| = target...")
print()

# theta_1 is odd and periodic. On (0, 1/2) it first increases then decreases.
# At z = 5/18 ~ 0.2778, we got 0.7782 which is ABOVE target 0.7768.
# Since theta_1 is increasing at z = 5/18 (still before the max),
# we need a slightly SMALLER z.

# Actually, let me first map out the theta_1 profile
print("Profile of |theta_1(z | omega)| near z = 5/18:")
print(f"{'z':>12} {'|theta_1|':>18} {'vs target':>12}")
print("-" * _sage_const_45 )

for z_num in [_sage_const_0p20 , _sage_const_0p22 , _sage_const_0p24 , _sage_const_0p25 , _sage_const_0p26 , _sage_const_0p27 , _sage_const_0p2750 , _sage_const_0p2770 , _sage_const_0p2778 , _sage_const_0p28 , _sage_const_0p29 , _sage_const_0p30 , _sage_const_0p32 , _sage_const_0p34 , _sage_const_0p36 , _sage_const_0p38 , _sage_const_0p40 , _sage_const_0p42 , _sage_const_0p44 , _sage_const_0p46 , _sage_const_0p48 , _sage_const_0p50 ]:
    val = theta1_abs(z_num)
    diff_pct = float((val - target) / target * _sage_const_100 )
    marker = " <-- 5/18" if abs(z_num - _sage_const_5 /_sage_const_18 ) < _sage_const_0p0001  else ""
    print(f"{z_num:>12.6f} {float(val):>18.15f} {diff_pct:>+11.4f}%{marker}")

print()

# Find both roots (one below and one above 1/4)
# theta_1 reaches max around z = 1/4 on this lattice

# Search in the range below the maximum
z_lo = R(_sage_const_0p15 )
z_hi = R(_sage_const_0p50 )

# First find maximum
z_max = R(_sage_const_0p25 )
for _ in range(_sage_const_50 ):
    z_a = z_max - R(_sage_const_0p0001 )
    z_b = z_max + R(_sage_const_0p0001 )
    if theta1_abs(z_a) < theta1_abs(z_b):
        z_max += R(_sage_const_0p00005 )
    else:
        z_max -= R(_sage_const_0p00005 )

val_max = theta1_abs(z_max)
print(f"Maximum of |theta_1| at z ≈ {float(z_max):.6f}, value = {float(val_max):.15f}")

if val_max < target:
    print(f"WARNING: Maximum {float(val_max)} is below target {float(target)}!")
    print("No solution exists on this interval.")
else:
    print(f"Maximum exceeds target by {float((val_max - target)/target*_sage_const_100 ):.4f}%")

print()

# Find z_0 on the LEFT branch (z < z_max) where |theta_1| = target
# Binary search
z_lo_l = R(_sage_const_0p15 )
z_hi_l = z_max

for _ in range(_sage_const_100 ):
    z_mid = (z_lo_l + z_hi_l) / R(_sage_const_2 )
    val = theta1_abs(z_mid)
    if val < target:
        z_lo_l = z_mid
    else:
        z_hi_l = z_mid

z0_left = (z_lo_l + z_hi_l) / R(_sage_const_2 )
val_left = theta1_abs(z0_left)
print(f"Left root:  z_0 = {float(z0_left):.15f}")
print(f"            |theta_1(z_0|omega)| = {float(val_left):.15f}")
print(f"            Error: {float(abs(val_left - target)/target):.2e}")

# Find z_0 on the RIGHT branch (z > z_max)
z_lo_r = z_max
z_hi_r = R(_sage_const_0p50 )

for _ in range(_sage_const_100 ):
    z_mid = (z_lo_r + z_hi_r) / R(_sage_const_2 )
    val = theta1_abs(z_mid)
    if val < target:
        z_hi_r = z_mid
    else:
        z_lo_r = z_mid

z0_right = (z_lo_r + z_hi_r) / R(_sage_const_2 )
val_right = theta1_abs(z0_right)
print(f"\nRight root: z_0 = {float(z0_right):.15f}")
print(f"            |theta_1(z_0|omega)| = {float(val_right):.15f}")
print(f"            Error: {float(abs(val_right - target)/target):.2e}")

# ============================================================
# Check if z_0 has a nice closed form
# ============================================================
print(f"\n{'='*_sage_const_60 }")
print("ANALYSIS: Does z_0 have a nice form?")
print(f"{'='*_sage_const_60 }")

z0 = z0_left  # The one near 5/18

print(f"\nz_0 = {float(z0):.15f}")
print(f"5/18 = {float(R(_sage_const_5 )/R(_sage_const_18 )):.15f}")
print(f"Difference: z_0 - 5/18 = {float(z0 - R(_sage_const_5 )/R(_sage_const_18 )):.15e}")
print()

# Check various nice fractions near z_0
print("Nearby nice fractions:")
for p in range(_sage_const_1 , _sage_const_30 ):
    for q_frac in range(p+_sage_const_1 , _sage_const_100 ):
        frac = R(p) / R(q_frac)
        if abs(frac - z0) < R(_sage_const_0p005 ):
            val_frac = theta1_abs(frac)
            diff_pct = float((val_frac - target) / target * _sage_const_100 )
            print(f"  {p}/{q_frac} = {float(frac):.10f}  |theta_1| = {float(val_frac):.10f}  ({diff_pct:+.4f}%)")

# Check algebraic numbers
print(f"\nAlgebraic candidates:")
for name, val in [
    ("1/(2*sqrt(2))", R(_sage_const_1 )/(_sage_const_2 *sqrt(R(_sage_const_2 )))),
    ("(sqrt(3)-1)/4", (sqrt(R(_sage_const_3 ))-_sage_const_1 )/R(_sage_const_4 )),
    ("1/(1+sqrt(3))", R(_sage_const_1 )/(R(_sage_const_1 )+sqrt(R(_sage_const_3 )))),
    ("ln(3)/(2*pi)", R(ln(R(_sage_const_3 )))/(_sage_const_2 *pi_val)),
    ("1/sqrt(5)", R(_sage_const_1 )/sqrt(R(_sage_const_5 ))),
    ("(sqrt(5)-1)/4", (sqrt(R(_sage_const_5 ))-_sage_const_1 )/R(_sage_const_4 )),
    ("3/(2*(1+sqrt(5)))", R(_sage_const_3 )/(R(_sage_const_2 )*(R(_sage_const_1 )+sqrt(R(_sage_const_5 ))))),
    ("ln(2)/sqrt(3)", R(ln(R(_sage_const_2 )))/sqrt(R(_sage_const_3 ))),
    ("2/sqrt(29)", R(_sage_const_2 )/sqrt(R(_sage_const_29 ))),
    ("sqrt(3)/sqrt(13)", sqrt(R(_sage_const_3 ))/sqrt(R(_sage_const_13 ))),
    ("1/sqrt(pi)", R(_sage_const_1 )/sqrt(pi_val)),
]:
    if abs(val - z0) < R(_sage_const_0p01 ):
        theta_val = theta1_abs(val)
        diff_pct = float((theta_val - target) / target * _sage_const_100 )
        print(f"  {name:>25} = {float(val):.10f}  |theta_1| = {float(theta_val):.10f}  ({diff_pct:+.4f}%)")

# ============================================================
# The INVERSE problem: what shift gives EXACTLY ln(3)/sqrt(2)?
# ============================================================
print(f"\n{'='*_sage_const_60 }")
print("KEY QUESTION: What IS z_0 exactly?")
print(f"{'='*_sage_const_60 }")

# z_0 satisfies |theta_1(z_0 | omega)| = ln(3)/sqrt(2)
# Let's see what 1/z_0 is, z_0^2, etc.
print(f"\nz_0 = {float(z0):.15f}")
print(f"1/z_0 = {float(R(_sage_const_1 )/z0):.15f}")
print(f"z_0^2 = {float(z0**_sage_const_2 ):.15f}")
print(f"z_0 * 18 = {float(z0 * R(_sage_const_18 )):.15f}")
print(f"z_0 * 36 = {float(z0 * R(_sage_const_36 )):.15f}")
print(f"z_0 * pi = {float(z0 * pi_val):.15f}")
print(f"z_0 * 2*pi = {float(z0 * _sage_const_2  * pi_val):.15f}")
print(f"z_0 * sqrt(3) = {float(z0 * sqrt(R(_sage_const_3 ))):.15f}")
print(f"z_0 * sqrt(2) = {float(z0 * sqrt(R(_sage_const_2 ))):.15f}")
print(f"sin(pi*z_0) = {float(R(sin(pi_val * z0))):.15f}")
print(f"cos(pi*z_0) = {float(R(cos(pi_val * z0))):.15f}")
print(f"tan(pi*z_0) = {float(R(tan(pi_val * z0))):.15f}")

# Also check: does the RIGHT root have a nice form?
z0r = z0_right
print(f"\nRight root z_0' = {float(z0r):.15f}")
print(f"1/z_0' = {float(R(_sage_const_1 )/z0r):.15f}")
print(f"z_0' * 6 = {float(z0r * R(_sage_const_6 )):.15f}")
print(f"z_0' * 12 = {float(z0r * R(_sage_const_12 )):.15f}")
print(f"1 - z_0' = {float(R(_sage_const_1 ) - z0r):.15f}")
print(f"1/2 - z_0' = {float(R(_sage_const_1 )/R(_sage_const_2 ) - z0r):.15f}")
print(f"(1/2 - z_0') * 18 = {float((R(_sage_const_1 )/R(_sage_const_2 ) - z0r) * R(_sage_const_18 )):.15f}")
print(f"z_0 + z_0' = {float(z0 + z0r):.15f}")  # Should be ~0.5 by symmetry

# ============================================================
# Alternative: Does any theta ratio give ln(3)/sqrt(2)?
# ============================================================
print(f"\n{'='*_sage_const_60 }")
print("THETA FUNCTION RATIOS")
print(f"{'='*_sage_const_60 }")

# Compute various theta functions at z = 5/18
z = R(_sage_const_5 ) / R(_sage_const_18 )
theta1_val = theta1_abs(z)

# theta_2(z|tau) = theta_1(z + 1/2 | tau)
theta2_val = theta1_abs(z + R(_sage_const_1 )/R(_sage_const_2 ))

# theta_3 and theta_4 (these are the "even" theta functions)
# theta_3(z|tau) = 1 + 2*sum q^{n^2} cos(2*n*pi*z)
theta3_val = R(_sage_const_1 )
for n in range(_sage_const_1 , _sage_const_300 ):
    q_pow = R(n)**_sage_const_2 
    theta3_val += R(_sage_const_2 ) * abs(q)**q_pow * R(cos(_sage_const_2 *n*pi_val*z))

# theta_4(z|tau) = 1 + 2*sum (-1)^n q^{n^2} cos(2*n*pi*z)
theta4_val = R(_sage_const_1 )
for n in range(_sage_const_1 , _sage_const_300 ):
    q_pow = R(n)**_sage_const_2 
    theta4_val += R(_sage_const_2 ) * (-_sage_const_1 )**n * abs(q)**q_pow * R(cos(_sage_const_2 *n*pi_val*z))

# eta value
gamma_13 = R(gamma(QQ(_sage_const_1 )/QQ(_sage_const_3 )))
eta_val = R(_sage_const_3 )**(R(_sage_const_1 )/R(_sage_const_8 )) * gamma_13**(R(_sage_const_3 )/R(_sage_const_2 )) / (R(_sage_const_2 ) * pi_val)

print(f"\nAt z = 5/18, tau = omega:")
print(f"  |theta_1| = {float(theta1_val):.15f}")
print(f"  |theta_2| = {float(theta2_val):.15f}")
print(f"  |theta_3| = {float(theta3_val):.15f}")
print(f"  |theta_4| = {float(theta4_val):.15f}")
print(f"  |eta|     = {float(eta_val):.15f}")
print(f"  target    = {float(target):.15f}")

print(f"\nRatios involving target:")
for name, val in [
    ("theta_1/eta", theta1_val/eta_val),
    ("theta_2/theta_3", theta2_val/theta3_val),
    ("theta_4/theta_3", theta4_val/theta3_val),
    ("theta_1/theta_3", theta1_val/theta3_val),
    ("theta_1*theta_4/(theta_2*theta_3)", theta1_val*theta4_val/(theta2_val*theta3_val)),
    ("eta^2/theta_1", eta_val**_sage_const_2 /theta1_val),
    ("theta_1^2/eta", theta1_val**_sage_const_2 /eta_val),
    ("theta_1*eta", theta1_val*eta_val),
    ("ln(theta_3/theta_4)", R(ln(theta3_val/theta4_val))),
    ("theta_3^2 - theta_4^2", theta3_val**_sage_const_2  - theta4_val**_sage_const_2 ),
]:
    v = float(val)
    diff_pct = (v - float(target)) / float(target) * _sage_const_100 
    match = " <-- MATCH!" if abs(diff_pct) < _sage_const_0p5  else ""
    print(f"  {name:<40} = {v:>15.10f}  ({diff_pct:+8.3f}%){match}")

# ============================================================
# The eta_omega^3 / (2*pi) combination
# ============================================================
print(f"\n{'='*_sage_const_60 }")
print("SPECIAL COMBINATIONS")
print(f"{'='*_sage_const_60 }")

# From the Chowla-Selberg formula, eta(omega) involves Gamma(1/3) and 3^{1/8}
# Check combinations of these constants
for name, val in [
    ("3^{1/8} * G(1/3)^{3/2} / (2pi)", R(_sage_const_3 )**(R(_sage_const_1 )/R(_sage_const_8 )) * gamma_13**(R(_sage_const_3 )/R(_sage_const_2 )) / (_sage_const_2 *pi_val)),
    ("eta(omega)", eta_val),
    ("eta^3", eta_val**_sage_const_3 ),
    ("eta^3 * sqrt(3)", eta_val**_sage_const_3  * sqrt(R(_sage_const_3 ))),
    ("3^{3/8} * eta^2", R(_sage_const_3 )**(R(_sage_const_3 )/R(_sage_const_8 )) * eta_val**_sage_const_2 ),
    ("sqrt(3/pi) * eta^2", sqrt(R(_sage_const_3 )/pi_val) * eta_val**_sage_const_2 ),
    ("G(1/3)^3 / (4*pi^2)", gamma_13**_sage_const_3  / (_sage_const_4 *pi_val**_sage_const_2 )),
    ("ln(3) / sqrt(2)", target),
    ("G(1/3)^3 / (4*pi^2) * 3^{1/4}", gamma_13**_sage_const_3  / (_sage_const_4 *pi_val**_sage_const_2 ) * R(_sage_const_3 )**(R(_sage_const_1 )/R(_sage_const_4 ))),
    ("2*pi * eta^2 / G(1/3)^{3/2}", _sage_const_2 *pi_val * eta_val**_sage_const_2  / gamma_13**(R(_sage_const_3 )/R(_sage_const_2 ))),
    ("G(1/3)^3 * 3^{1/4} / (8*pi^2)", gamma_13**_sage_const_3  * R(_sage_const_3 )**(R(_sage_const_1 )/R(_sage_const_4 )) / (_sage_const_8 *pi_val**_sage_const_2 )),
]:
    v = float(val)
    diff_pct = (v - float(target)) / float(target) * _sage_const_100 
    match = " <-- EXACT" if abs(diff_pct) < _sage_const_0p01  else (" <-- CLOSE" if abs(diff_pct) < _sage_const_1  else "")
    print(f"  {name:<45} = {v:>15.10f}  ({diff_pct:+8.4f}%){match}")

# Can eta(omega) be expressed as exp(ln(3)/sqrt(2) + correction)?
print(f"\nln(eta(omega)) = {float(R(ln(eta_val))):.15f}")
print(f"ln(3)/sqrt(2) - 1 = {float(target - R(_sage_const_1 )):.15f}")
print(f"eta = exp(ln(3)/sqrt(2) * x) where x = {float(R(ln(eta_val)) / target):.15f}")

# ============================================================
# DIRECT TEST: |theta_1(z|omega)| at z = ln(3)/(pi*sqrt(6))
# ============================================================
# This shift would mean the Wilson line is determined by ln(3)
z_test = R(ln(R(_sage_const_3 ))) / (pi_val * sqrt(R(_sage_const_6 )))
theta_test = theta1_abs(z_test)
print(f"\n|theta_1(ln(3)/(pi*sqrt(6)) | omega)| = {float(theta_test):.15f}  vs target {float(target):.15f}")

z_test2 = R(ln(R(_sage_const_3 ))) / (R(_sage_const_2 ) * pi_val)
theta_test2 = theta1_abs(z_test2)
print(f"|theta_1(ln(3)/(2*pi) | omega)| = {float(theta_test2):.15f}  vs target {float(target):.15f}")

z_test3 = target / pi_val
theta_test3 = theta1_abs(z_test3)
print(f"|theta_1(ln(3)/(pi*sqrt(2)) | omega)| = {float(theta_test3):.15f}  vs target {float(target):.15f}")

print(f"\n{'='*_sage_const_60 }")
print("COMPUTATION COMPLETE")
print(f"{'='*_sage_const_60 }")

